security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAthenticatorAuthenticator
            logout:
                path: app_logout
                target: app_login # Redirige vers la page de connexion après déconnexion
                

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
    # Empêche les admins d'accéder à la page d'accueil
    # - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # Permet uniquement aux admins d'accéder au tableau de bord admin
    - { path: ^/admin/dashboard, roles: ROLE_ADMIN }

    # Permet aux utilisateurs classiques d'accéder à la page d'accueil ou d'autres pages
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/appointment, roles: ROLE_USER }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
